### PR TITLE
Respect prefix when calculating the IPv6

### PR DESCRIPTION
**Pull request by cromefire**
Because the FritzBox sometimes reports different prefix lengths (XXXX:XXXX:XXXX:XXX1/64 for push and XXXX:XXXX:XXXX:XX/56 for polling). Because of that the prefix needs to be respected so ::1:XXXX:XXXX:XXXX:XXXX will correctly add the 1 to the /56 prefix, but not the /64 prefix.

Also did some updates, because why not.

### CODE REVIEW

**Comment by adrianrudnik** [comment]
Hi there @cromefire , nice work, sadly I currently do not have any box to test it against. I could merge it, but maybe you want to take over the ownership of this repo? I could transfer it if you like.  Otherwise give me some time to review and merge it :)

**Comment by cromefire** [comment]
🤷🏻‍♂️ I can, if you want to. I still have one for now and actively use it and have to deal with the weird stuff the internet provider and the box think of.

**Comment by adrianrudnik** [comment]
Ok, I will merge this PR now, then you seem to need to delete your fork, as the transfer throws an error as a similar project already exists in your account. You should get a transfer request then that you need to approve.

**Comment by adrianrudnik** [comment]
Ok, merge is done, feel free to free the namespace of the repo on your side, so I can initiate the transfer. I hope the other PR that was still open transfers as well.

**Comment by cromefire** [comment]
Removed my fork

**Comment by adrianrudnik** [comment]
Cool, worked, transfer seems complete.

**Pull request merged**
